categories:
  - cond-mat.mtrl-sci
  - cond-mat.soft
  - physics.app-ph
  - physics.flu-dyn

must_include:
  - droplet motion
  - kinetic friction

boost_keywords:
  - surface charging


llm_score_threshold: 5
max_papers_per_run: 100